<?php

namespace AppBundle\Repository;

/**
 * imageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getImageBySlug($image_slug)
    {
        $em= $this->getEntityManager();
        $qb=$em->createQueryBuilder();
        $query = $qb->select('r')
            ->from('AppBundle:Image','r')
            ->where('r.slug = :imageslug')
            ->setParameter('imageslug', $image_slug)
            ->getQuery();
        $image=$query->getResult();
        return $image;
    }
}
