<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Room;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvailableRoom($start_date,$end_date)
    {
        $start=$start_date->format('Y-m-d');
        $end=$end_date->format('Y-m-d');


        $em= $this->getEntityManager();
        $qb= $em->createQueryBuilder();
        $nots= $em->createQuery("SELECT IDENTITY(b.room) FROM AppBundle:Reservation b WHERE  NOT (b.dateOut < '$start' OR b.dateIn > '$end')");
        $dql_query = $nots->getDQL();
        $qb->resetDQLParts();

        $queryav= $qb->select('r')
            ->from('AppBundle:Room' ,'r')
            ->where($qb->expr()->notIn('r.id',$dql_query))
            ->getQuery();

        $available_room = $queryav->setMaxResults(1)->getResult();

        return $available_room;

    }

    public function freeRooms($end_date)
    {
        $dsystem=$end_date->format('Y-m-d');
        $em= $this->getEntityManager();
        $query = $em->createQuery(
            'DELETE AppBundle:Reservation b 
               WHERE b.dateOut < :dsystem')
            ->setParameter("dsystem", $dsystem);

        $query->execute();

    }

    public function studenthavereservation($email)
    {
//        $em= $this->getEntityManager();
//        $qb= $em->createQueryBuilder();
//        $nots= $em->createQuery("SELECT IDENTITY(b.id) FROM AppBundle:Student b WHERE (b.email = '$email' )");
//        $sresult=$nots->getResult();
//
//        $queryav= $qb->select('r')
//            ->from('AppBundle:Reservation' ,'r')
//            ->where('r.student = :rstudent')
//            ->setParameter(':rstudent',$sresult)
//            ->getQuery();
//        $res=$queryav->execute();
//        if(!empty($res)){
            return false;
//        }
//        else
//            return false;


    }

}







